### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Estrella1024** [UoA-eResearch/leapmotion_gestures#10]
Sorry, I just turned off this comment by accident.

question:
I can run predict_gui.py successfully and output gestures. But the information output by predict.py is bad frame.

**Comment by Estrella1024** [comment]
![image](https://user-images.githubusercontent.com/56550662/96397785-db15c580-11fc-11eb-9173-40303fc2fccb.png)
![image](https://user-images.githubusercontent.com/56550662/96397870-0f898180-11fd-11eb-8240-2e1a2af592c6.png)

**Comment by aleathwick** [comment]
See my reply in your original issue: https://github.com/UoA-eResearch/leapmotion_gestures/issues/8#issuecomment-711491935
