### ISSUE TITLE
Importing config

### ISSUE THREAD

**Issue by chinmaychinara91** [UoA-eResearch/leapmotion_gestures#13]
Hi,

I wanted to record some fresh data using your recorder. I did pip install config but it gives me this error of "AttributeError: module 'config' has no attribute 'devices'". I was wonedring is this config.py something locally defined at your and not in the repo ? Kindly let me know how to tackle this.

**Comment by neon-ninja** [comment]
Hi @chinmaychinara91 - create a file called config.py similar to https://github.com/UoA-eResearch/leapmotion_gestures/blob/record_only/config.example.py with your specific configuration

**Comment by chinmaychinara91** [comment]
got it thanks :)
