### ISSUE TITLE
Difference in ordering of column names in csv file

### ISSUE THREAD

**Issue by chinmaychinara91** [UoA-eResearch/leapmotion_gestures#15]
1. I ran the record.exe (v-0.3 release) and saved the csv file. I get the columns as:
currentFrameRate, device_index, device_mode, gesture, id, [hands items], timestamp

2. I ran the record.py (v-0.3 tag) and saved the csv file, I get the columns as:
currentFrameRate, id, timestamp, device_index, device_mode, [hands items], gesture

Why this difference? Can you point me to the code which handles this ordering ?

**Comment by neon-ninja** [comment]
Here is the line of code that outputs to CSV - https://github.com/UoA-eResearch/leapmotion_gestures/blob/master/record.py#L138

The column ordering would be implicit, based on the order of keys in the underlying dictionaries.

I don't think this would cause any problems as values are accessed by column name, not index.

**Comment by chinmaychinara91** [comment]
@neon-ninja thanks now it is very clear
