### ISSUE TITLE
One question regarding config.devices

### ISSUE THREAD

**Issue by hlihli0316** [UoA-eResearch/leapmotion_gestures#17]
Hi, I have a question regarding the config.devices on line 74 in predict.py. When I compile this module, it says there is no attribute called "devices" in config. I have searched the config which belongs to pypi but get no useful information about this 'devices'. Could you please give me any information about that?

**Comment by hlihli0316** [comment]
I am sorry that I just see this question has been asked in the issues..  Could you please give me more information regarding this line {"url": "ws://localhost:6437/v6.json", "mode": "desktop"}. What is the meaning of  "ws://localhost:6437/v6.json" here. If I use laptop, should I change the mode to "laptop"? Could you please share any useful material regarding to it.

**Comment by neon-ninja** [comment]
This URL refers to the websocket endpoint served by the leap motion software. Desktop means the leapmotion is flat on the desk, with your hands above it, as opposed to the head mounted alternative

**Comment by hlihli0316** [comment]
Thank you for your reply. It solves my question.

Right now, another issue arise which is similar to #8. I can only receive "bad frames". I follow the advice given by aleathwick, and here is the error I got:

Traceback (most recent call last):
  File "C:\Users\nklih\Desktop\leapmotion_gestures-master\predict.py", line 155, in <module>
    frames[frame_index, i] = (packed_frame[v] - means_dict[v]) / stds_dict[v]
KeyError: 'right_elbow_0'

It seems that some key value in VoI is not in the packed_frame. How can I solve this problem..

**Comment by neon-ninja** [comment]
Make sure you have V4 (v4.0.0+52173) of the leap motion SDK. Try predict_gui instead of predict

**Comment by hlihli0316** [comment]
Thank you for your reply.

My leap motion sdk is v4.0.0+52173. And I try predict_gui instead but got the following error:

  File "C:\Users\nklih\Desktop\leapmotion_gestures-master\predict_gui.py", line 13, in <module>
    import keras
  File "C:\Users\nklih\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\__init__.py", line 20, in <module>
    from . import initializers
  File "C:\Users\nklih\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\initializers\__init__.py", line 124, in <module>
    populate_deserializable_objects()
  File "C:\Users\nklih\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\initializers\__init__.py", line 82, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'

Could you tell me what kind of keras it requires?  My keras version is 2.4.3 and tensorflow version is 2.5.0.

**Comment by neon-ninja** [comment]
Your versions of tensorflow and keras are incompatible with each other. See https://github.com/keras-team/keras/issues/14632

**Comment by hlihli0316** [comment]
Thank you for your reply. 

It works after I replace keras with tf.keras. 

May I ask where you get the information about how to use websocket to interact with leap motion. Like the following code:

            for i, device in enumerate(config.devices):
                frames_total += 1
                if i not in websocket_cache:
                    ws = websocket.create_connection(device["url"])
                    if device["mode"] == "desktop":
                        ws.send(json.dumps({"optimizeHMD": False}))
                    else:
                        ws.send(json.dumps({"optimizeHMD": True}))
                    version = ws.recv()
                    print(i, version)
                    websocket_cache[i] = ws

I have searched several places but cannot get useful information about it. Could you please give me the source of this kind of information so that I can learn more by myself.

**Comment by neon-ninja** [comment]
https://developer-archive.leapmotion.com/documentation/javascript/supplements/Leap_JSON.html

https://developer-archive.leapmotion.com/documentation/javascript/devguide/Leap_Architecture.html

**Comment by hlihli0316** [comment]
Thank you so much for your reply. I learned a lot from these two links.

May I ask you some more questions:

1) In the predict.py, why you use a for loop  "for i, device in enumerate(config.devices):". Since there is only one device and one socket. Is that for some future extension?

2) For the data in the params/means_dict.json and params/stds_dict.json, from which place do you get the data in these two files. Is that you calculated from your training data?

3) How do you define the start and end of a dynamic gesture. From my point of view, in one cycle you accumulate a certain number of data frames and put all these data into the RNN to classify. After you get the result of this cycle, you start over this process again. So there is no function to detect the start and end of each move, the different cycle of recorded frame separate each dynamic gesture temporally by force. Is my understand correct?

I am sorry that I ask so many questions...

**Comment by neon-ninja** [comment]
1. Yes. As per https://github.com/UoA-eResearch/leapmotion_gestures/issues/4, the plan was to use multiple devices, potentially in different configurations (one desktop, one HMD (or like a necklace))

2. As per the readme, these dictionaries are generated in the notebooks

3. Yes, it's up to the LSTM to figure out where one gesture ends and another begins

**Comment by aleathwick** [comment]
@hlihli0316 a couple more comments on your questions:

2. Yes those dictionaries are calculated using the training set.

3. What you say here is true: "After you get the result of this cycle, you start over this process again. So there is no function to detect the start and end of each move". But for the predict script with gui (`predict_gui.py`), the prediction cycles can overlap e.g. if a model requires ~1 second of data to make a prediction, then predictions can be made every ~0.5 seconds. With no detection of gesture starts/ends, it is possible a cycle will contain the end of one gesture and the beginning of another, which normally produces a prediction with low confidence. In the gui version, the current gesture displayed is not updated unless the predicted gesture is predicted with confidence above a minimum threshold.
The models we ended up using are many-to-one models, i.e. given many input frames, produce a single prediction (see `exploration-many2one.ipynb`). We also briefly considered many-to-many models, i.e. given many input frames, produce a prediction for every single one, in which case gesture changes in the middle of cycles could be recognized (see `exploration-many2many.ipynb`).

**Comment by neon-ninja** [comment]
Here's the specific line of code where these dictionaries are generated: https://github.com/UoA-eResearch/leapmotion_gestures/blob/4e526b02f77e1dd78c7a0ad2623a00440907d5a8/src/data_methods.py#L50

**Comment by hlihli0316** [comment]
Thank you so much for your help.. I am sorry that I reply so late... So the mean and median of these features are based on all kinds of movements(i.e. all the movements together produce 1 median and 1 mean in total for each feature). Is that true?

**Comment by aleathwick** [comment]
Yes that's correct. For a given feature, its mean and standard deviation are calculated from the entire training set across all movements/gestures.

**Comment by hlihli0316** [comment]
Thank you for your reply. Also, I have a question regarding the training process, in the X_y2examples function, which is in data_methods.py, the stride is set to n_frames/2. Why do not use n_frames instead since n_frames/2 will cause some overlap.

**Comment by aleathwick** [comment]
We were collecting training data ourselves, which was time consuming. Some overlap makes the training data go further. i.e. 2000 overlapping training examples are better than 1000 non-overlapping training examples.

**Comment by hlihli0316** [comment]
So that is to say there is no need to take care of the time stamp(regarding to the start of the move) of each input node(whose total size is #_of_accumulated_frames * #_of_features_in_each_frame) as long as they represent the corresponding feature of the accumulated data frame. Is that correct?

**Comment by hlihli0316** [comment]
Also, may I ask two more questions: 
1) I realize that in the params/mean_dict.json and params/stds_dict.json, there are several feature names that I cannot find in the traning data, even when I use your record.py. For example, there is no feature called 'left_f5_p_plain'. I am sure my sdk version is the same as required. Could you please give me any advice on that?

2) For the shape of input data, I realize it is a 3d data whose shape is (5468, 10, 50) which is gotten from function folder2examples. I am wondering how can I reshape it into the shape like #_sample * #_feature so that it can fit some other models. 

Thank you.

**Comment by aleathwick** [comment]
Yes the time stamp of the start of the move doesn't matter, so long as all frames accumulated are from the same gesture.

Your other questions:
1. There are extra features that are derived from the raw output of the leap motion sensor. 'left_f5_p_plain' is the distance of the left hand's little finger to the plain defined by the palm of the left hand, and is calculated here: https://github.com/UoA-eResearch/leapmotion_gestures/blob/4e526b02f77e1dd78c7a0ad2623a00440907d5a8/src/features.py#L54-L57
2. folder2examples will take a folder of csv files and convert them into training data. As you say, the training data as output from folder2examples will be #_training_examples * #_frames_per_example * #_features. You can specify the frames per example using the `n_frames` argument of folder2examples to fit models that take a different number of frames - is that what you mean? Or, if you want to apply preprocessing to a file but without splitting it into discreet examples, you could use the first lines of this function, before it calls X_y2examples: https://github.com/UoA-eResearch/leapmotion_gestures/blob/4e526b02f77e1dd78c7a0ad2623a00440907d5a8/src/data_methods.py#L303-L315

**Comment by neon-ninja** [comment]
Note plain should be plane (https://en.wikipedia.org/wiki/Plane_(geometry))

**Comment by hlihli0316** [comment]
I got your point. Thank you both so much for your detailed reply.

**Comment by hlihli0316** [comment]
May I ask one more question.. I noticed that in your training dataset, there is no feature like "f5_f5", but if I need to use this feature as a VoI, I need to calculate its mean and standard deviation for normalization so that I need to record these derived features in record.py, is that correct?

**Comment by hlihli0316** [comment]
Hi, May I ask you a question again. I move to a new machine and get this error: 

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

I have turned off all my firewalls on that computer but still cannot fix this problem. Could you give me any advice on it.

**Comment by neon-ninja** [comment]
You'd also need to go into the leapmotion settings and bind to 0.0.0.0 instead of local host, IIRC

Edit: Option is called `websockets_allow_remote`, see https://developer-archive.leapmotion.com/documentation/cpp/devguide/Leap_Configuration.html

**Comment by hlihli0316** [comment]
Thank you so much for your reply. 

Could you please give me more details. Do you mean I need to change the "url" in config.py to "0.0.0.0"(i.e. "url" : "ws: 0.0.0.0")?  Do I need to do this reset every time I use a new machine to run this program?

Edit: I have change the file of config.json and add these sentences into it:

{
  "configuration": {
    "websockets_enabled": true,
    "websockets_allow_remote": false,
    "ws_port": 51000,
    "wss_port": 51001
  }
}

Are these parameters correct?

Also, when I hope to run this file to update the leapmotion parameter using LeapSvc, it says LeapSvc is not recognized although I have already installed the leapmotion sdk which contains this file. Could you please give me any advice on it?

**Comment by neon-ninja** [comment]
No, the config.py for this repo is different from the config.json for the leap motion software. As described in the link I gave you, config.json should be in one of %AppData%/Leap Motion or %ProgramData%/Leap Motion. Just restart the leap motion service after modifying this file

**Comment by hlihli0316** [comment]
Thank you for your reply. With your help I found my problem. I forget to choose Allow Web Apps in the control panel. Now the problem is solved. Thank you.

**Comment by neon-ninja** [comment]
Oh, I thought you were trying to access a leap motion connected to one pc from another pc

**Comment by hlihli0316** [comment]
May I ask you a dumb question again.... Where do you find anything about the V4 version API of the data frame of leap motion written in python(i.e. where I can get the full list of the data frame keys). I found a lot of spaces but only find c++ version and not found any official version written in python. Could you please give me any hint. 

Edited: To make my question more clear, I can find the key names from the result csv files but cannot make sure some of those meaning. Are they the same as their corresponding parts in the LeapC version API.

**Comment by neon-ninja** [comment]
See https://developer-archive.leapmotion.com/documentation/javascript/supplements/Leap_JSON.html. It's not Python, it's JSON
