### ISSUE TITLE
module 'config' has no attribute 'devices'

### ISSUE THREAD

**Issue by hdongv** [UoA-eResearch/leapmotion_gestures#5]
File "record.py", line 76, in <module>
    packed_frame = collect_frame(frames_total, n, websocket_cache)
  File "D:\Job\Gestures\Test\UoA-eResearch\leapmotion_gestures-master\src\leap_methods.py", line 24, in collect_frame
    for i, device in enumerate(config.devices):
AttributeError: module 'config' has no attribute 'devices'

**Comment by neon-ninja** [comment]
Hi @hdongv  - create a file called config.py similar to https://github.com/UoA-eResearch/leapmotion_gestures/blob/record_only/config.example.py with your specific configuration

**Comment by hdongv** [comment]
Hi@neon-ninja , It worked, Thank you very much!
