### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Estrella1024** [UoA-eResearch/leapmotion_gestures#6]
print(device["mode"] == "desktop")
TypeError: string indices must be integers

why?

what can I do?

**Comment by neon-ninja** [comment]
Check your config.py looks similar to https://github.com/UoA-eResearch/leapmotion_gestures/blob/record_only/config.example.py

**Comment by Estrella1024** [comment]
> 检查您的config.py是否类似于https://github.com/UoA-eResearch/leapmotion_gestures/blob/record_only/config.example.py

Thank you very much, my problem is solved.
